name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-24.04
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-24.04
            c_compiler: cl
            
    steps:
    - uses: actions/checkout@v4
    
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      
    - name: Setup Python
      if: runner.os == 'Windows'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Python Dependencies
      if: runner.os == 'Windows'
      run: pip install meson ninja

    - name: Install build tools on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt install meson ninja-build pkgconf
        
    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'

    - name: Prepare Build
      run: meson setup build
      
    - name: Run Build
      run: meson compile -v -C build
      
    - name: Run Test Suite
      run: meson test -v -C build

    - name: windeployqt
      if: runner.os == 'Windows'
      run: |
        mkdir target
        cp ./build/qt6-test.exe target/
        windeployqt ./target/qt6-test.exe

    - name: copy to target
      if: runner.os == 'Linux'
      run: |
        mkdir target
        cp ./build/qt6-test target/

    - uses: actions/upload-artifact@v4
      with:
        name: 'target_${{ matrix.os }}'
        path: './target/'
