name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write

    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
            
    steps:
    - uses: actions/checkout@v4
    
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      
    - name: Setup Python
      if: runner.os == 'Windows'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Python Dependencies
      if: runner.os == 'Windows'
      run: pip install meson ninja
      
    - name: Prepare MSVC
      if: runner.os == 'Windows'
      uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: x64
        
    - name: Install Qt6 on Windows
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'

    - name: Install Qt6 and meson on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install meson ninja-build pkgconf
        sudo apt install -y qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools libqt6widgets6

    - name: Prepare Build
      run: meson setup build
      
    - name: Run Build
      run: meson compile -v -C build
      
    - name: Run Test Suite
      run: meson test -v -C build

    - uses: vimtor/action-zip@v1.2
      with:
        files: build/
        dest: build_${{ matrix.os }}-${{ matrix.c_compiler }}.zip

    - uses: actions/upload-artifact@v4
      with:
        name: build_files
        path: '${{ github.workspace }}/build_${{ matrix.os }}-${{ matrix.c_compiler }}.zip'
